version: '3.8'


services:
  
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: services/Dockerfile
    ports:
      - 0.0.0.0:8080:8080
    restart: on-failure
    command: npm run start --host 0.0.0.
    env_file:
      - services/.env.production
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 3000:3000
    restart: on-failure

  proxy:
    container_name: proxy
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - backend
      - frontend



      