version: '3.8'


services:

  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_DB: OURTUBE
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./services/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: .services/Dockerfile
    ports:
      -8080:8080
    restart: on-failure
    depends_on:
      - db
      
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: .client/Dockerfile
    ports:
      -5173:5173
    restart: on-failure
    depends_on:
      - db