export const EVENTS = {
  INIT_PLAYLIST: 'initPlaylist',
  GET_PLAYLIST: 'getPlaylist',
  UPDATE_PLAYLIST: 'updatePlaylist',
  PLAYLIST_ENDED: 'playlistEnded',
  USER_OF_PLAYBACK_LOGOUT: 'userOfPlaybackLogout',
  ADD_USER: 'addUser',
  USER_ADDED: 'userAdded',
  REMOVE_USER: 'removeUser',
  USER_REMOVED: 'userRemoved',
  START_PLAYLIST: 'startPlaylist',
  PLAYLIST_STARTED: 'playlistStarted',
  UPDATE_USER: 'updateUser',
  ERROR: 'error',
  INIT_USERS: 'initUsers',
  PLAYBACK_INIT: 'initPlayback',
  GET_PLAYBACK: 'getPlayback',
  NEXT_VIDEO: 'nextVideo',
  PLAYBACK_UPDATED: 'playbackUpdated',
  SEND_CHAT_MSG: 'sendChatMsg',
  RESEND_CHAT_MSG: 'resendChatMsg',
  ADD_VOTE: 'addVote',
  UPDATED_VOTING_RESULTS: 'updateVotingResults',
};
