name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: services/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: client/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Build and push proxy image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: nginx/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/proxy:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
        - name: Pull backend image from docker hub
          run: docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
        - name: Pull frontend image from docker hub
          run: docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
        - name: Pull proxy image from docker hub
          run: docker pull ${{ secrets.DOCKER_USERNAME }}/proxy:latest
        - name: Run Docker compose
          run: docker compose -f docker-compose.production.yml build --no-cache
          env:
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
